[workspace]
authors = ["Seth Stadick <sstadick@gmail.com>"]
platforms = ["linux-64"]
preview = ["pixi-build"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge", "https://prefix.dev/pixi-build-backends", "https://repo.prefix.dev/modular-community"]

[package]
name = "greetings"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-mojo", version = "0.1.*" }

[tasks]
b = "pixi build --output-dir ./target"

#[package.build.configuration]
# This is entirey optional. pixi install is recommended
#dist-dir = "./target"
#env = { "TEST" = "FOUND" }

#[[package.build.configuration.bins]]
#name = "greet"
#path = "./main.mojo"
#extra-args = ["-I", "."]
#extra-input_globs = ["**/.c"]

[package.build.configuration.pkg]
name = "greetings"
#path = "greetings"
#extra-args = ["-I", "."]
#extra-input_globs = ["**/.c"]

[package.host-dependencies]
max = "=25.4.0"

[package.build-dependencies]
max = "=25.4.0"
small_time = ">=25.4.1,<26"
extramojo = ">=0.16.0,<0.17"

[package.run-dependencies]
max = "=25.4.0"

[dependencies]
max = "=25.4.0"
small_time = ">=25.4.1,<26"
extramojo = ">=0.16.0,<0.17"
greetings = { path = "." }
